name: .NET

on:
    push:
        branches: [main, master]
        schedule:
            - cron: "0 0 1 * *"

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                dotnet: ["5.0.102"]

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: ${{ matrix.dotnet }}
            - name: Install dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --configuration Release --no-restore
